// <auto-generated />
using ErrorNpgsql.Datas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ErrorNpgsql.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20240517064727_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ErrorNpgsql.Models.MyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id")
                        .HasName("pk_my_entity");

                    b.ToTable("my_entity", "public");
                });

            modelBuilder.Entity("ErrorNpgsql.Models.MyEntity", b =>
                {
                    b.OwnsMany("System.Collections.Generic.List<ErrorNpgsql.Models.JsonbField>", "JsonbFields", b1 =>
                        {
                            b1.Property<int>("MyEntityId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("Capacity")
                                .HasColumnType("integer");

                            b1.HasKey("MyEntityId", "Id")
                                .HasName("pk_my_entity");

                            b1.ToTable("my_entity", "public");

                            b1.ToJson("jsonb_fields");

                            b1.WithOwner()
                                .HasForeignKey("MyEntityId")
                                .HasConstraintName("fk_my_entity_my_entity_my_entity_id");
                        });

                    b.Navigation("JsonbFields");
                });
#pragma warning restore 612, 618
        }
    }
}
